# Generated by Django 2.1.4 on 2019-01-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_goal_note_post_profile_resource_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='email',
            field=models.EmailField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='resource',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
