# Generated by Django 2.1.5 on 2019-01-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190108_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='subgoal',
        ),
        migrations.RemoveField(
            model_name='note',
            name='goal',
        ),
    ]
